config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  resources :users, only: %i[index show edit update destroy] do
    get '/profile', to: 'users#profile'
  end

  resources :restaurants do
    resources :reviews, only: %i[create destroy]
    # resources :categories, only: %i[new create destroy]
    get '/order', to: 'restaurants#order'
  end

  resources :carts, only: [] do
    collection do
      post 'add_to_cart'
      patch 'cart_update'
      delete 'remove_from_cart'
    end
  end

  resources :orders, only: %i[index show] do
    collection do
      post 'create_order'
      patch 'order_status'
    end
  end

  resources :categories, only: %i[show new create edit update destroy] do
    resources :foods, only: %i[new create]
  end

  resources :foods, only: [:show]

  root 'home_pages#home'

  get '/all_orders', to: 'orders#all_orders'
  get '/help', to: 'home_pages#help'
  get '/about', to: 'home_pages#about'
  get '/contact', to: 'home_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :cart_items
  has_many :foods, through: :cart_items

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id restaurant_id updated_at user_id]
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :food

  # validates :quantity, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :restaurant_categories, dependent: :destroy
  has_many :restaurants, through: :restaurant_categories
  has_many :foods, dependent: :destroy

  has_one_attached :category_image

  validates :category_name, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[category_image category_name created_at id updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[category_image_attachment category_image_blob foods restaurant_categories restaurants]
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
  has_many :restaurant_foods, dependent: :destroy
  has_many :restaurants, through: :restaurant_foods

  validates :food_name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }

  def self.ransackable_attributes(_auth_object = nil)
    %w[category_id created_at food_name id price updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[category restaurant_foods restaurants]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  paginates_per 5

  belongs_to :user
  belongs_to :restaurant
  has_many :order_items
  has_many :foods, through: :order_items

  enum :order_status, %i[pending accepted rejected], default: :pending

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id order_status restaurant_id total_amount updated_at user_id]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[foods order_items restaurant user]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :food

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at food_id id order_id quantity updated_at]
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  paginates_per 4

  has_many :reviews, dependent: :destroy
  has_many :restaurant_categories, dependent: :destroy
  has_many :categories, through: :restaurant_categories
  has_many :restaurant_foods, dependent: :destroy
  has_many :foods, through: :restaurant_foods
  has_many :orders, dependent: :destroy

  has_one_attached :restaurant_image

  accepts_nested_attributes_for :restaurant_categories, allow_destroy: true
  accepts_nested_attributes_for :restaurant_foods, allow_destroy: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :restaurant_name, presence: true
  validates :restaurant_address, presence: true
  validates :restaurant_contact, presence: true,
                                 length: { maximum: 10, minimum: 10 }
  validates :restaurant_email, presence: true,
                               format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id restaurant_address restaurant_contact restaurant_details restaurant_email restaurant_image
       restaurant_name status updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[categories foods orders restaurant_categories restaurant_foods restaurant_image_attachment restaurant_image_blob
       reviews]
  end
end

app/models/restaurant_food.rb
class RestaurantFood < ApplicationRecord
  belongs_to :restaurant
  belongs_to :food

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at food_id id price restaurant_id updated_at]
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  def self.ransackable_attributes(_auth_object = nil)
    %w[content created_at id restaurant_id updated_at user_id]
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true


  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify

  def self.ransackable_associations(_auth_object = nil)
    %w[resource users]
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id name resource_id resource_type updated_at]
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  paginates_per 5

  after_create :assign_default_role

  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :reviews
  has_one :cart
  has_many :orders

  validates :username, presence: true, length: { maximum: 15 }
  validates :email, length: { maximum: 255 }, format: { with: email_regexp }
  validates :address, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[address confirmation_sent_at confirmation_token confirmed_at created_at email encrypted_password id
       remember_created_at reset_password_sent_at reset_password_token unconfirmed_email updated_at username]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[cart orders reviews roles]
  end

  private

  def assign_default_role
    add_role(:member) if roles.blank?
  end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def home
    # redirect_to new_user_session_path if current_user.nil?
    @categories = Category.all
    @outlets = Restaurant.all
  end

  def help; end

  def about; end

  def contact; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Food Vault'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end

  def admin?
    current_user.has_role? :admin
  end

  def set_cart
    if current_user.cart.present?
      current_user.cart
    else
      Cart.create(restaurant_id: params[:restaurant_id], user: current_user)
    end
  end

  def cart_item_exist?(food)
    cart_item = set_cart.cart_items.find_by(food:)
    cart_item.present?
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, option = { size: 80 })
    size = option[:size]
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'gravatar')
  end
end

app/views/home_pages/_category_page.html.erb
<div class="row">
  <p style="float: left">
    Categories:
  </p>
  <div class="col">
    <div class="card-group ">
      <div class="d-flex flex-row flex-nowrap overflow-auto">
        <% category.each do |type| %>
          <div class="card me-3" style="min-width: 200px">
            <a href=<%= category_path(type)%>>
              <%= image_tag type.category_image, size: "200x200" %>
            </a>
            <div class="card-body">
              <h5 class="card-title"><%= type.category_name %></h5>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home_pages/_outlets_page.html.erb
<div class="row">
  <p style="float: left">
    Restaurants:
  </p>
  <div class="col">
    <div class="card-group ">
      <div class="d-flex flex-row flex-nowrap overflow-auto">
        <% outlet.each do |outlet| %>
          <div class="card me-3" style="min-width: 202px">
            <a href=<%=restaurant_path(outlet)%>>
              <%= image_tag outlet.restaurant_image, size: "200x200" %>
            </a>
            <div class="card-body">
              <h5 class="card-title"><%= outlet.restaurant_name %></h5>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="#">Food Circle</a> is a online food ordering website application, whose motive is to deliver food to our hungry users.
</p>

app/views/home_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact Food Circle about the web application at the 
  <a href="#">Contact page</a>.
</p>

app/views/home_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on Food Vault at the
  <a href="#">Food vault help page</a>.
</p>

app/views/home_pages/home.html.erb
<% if user_signed_in? %>
  <span class="all-category">
    <%= render 'category_page', category: @categories %>
  </span>

  <span class="all-outlets">
    <%= render 'outlets_page', outlet: @outlets %>
  </span>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to Food Vault!</h1>
    <h2>
      This is the home page for <a href="#">Food Vault</a> web application.
    </h2>
    <%= button_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary", method: :get %>
  </div>
<% end %>