config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  resources :users, only: %i[index show edit update destroy] do
    get '/profile', to: 'users#profile'
  end

  resources :restaurants do
    resources :reviews, only: %i[create destroy]
    # resources :categories, only: %i[new create destroy]
    get '/order', to: 'restaurants#order'
  end

  resources :carts, only: [] do
    collection do
      post 'add_to_cart'
      patch 'cart_update'
      delete 'remove_from_cart'
    end
  end

  resources :orders, only: %i[index show] do
    collection do
      post 'create_order'
      patch 'order_status'
    end
  end

  resources :categories, only: %i[show new create edit update destroy] do
    resources :foods, only: %i[new create]
  end

  resources :foods, only: [:show]

  root 'home_pages#home'

  get '/all_orders', to: 'orders#all_orders'
  get '/help', to: 'home_pages#help'
  get '/about', to: 'home_pages#about'
  get '/contact', to: 'home_pages#contact'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :cart_items
  has_many :foods, through: :cart_items

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id restaurant_id updated_at user_id]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def add_to_cart
    authorize set_cart
    set_cart.cart_items.create(food_id: params[:food_id])
    redirect_to request.referrer
  end

  def remove_from_cart
    authorize set_cart
    cart_item = set_cart.cart_items
                        .find_by(food_id: params[:food_id])
    cart_item.destroy
    redirect_to request.referrer
  end

  def cart_update
    authorize set_cart
    cart_item = set_cart.cart_items
                        .find_by(food_id: params[:cart_item][:food_id])

    cart_item.update(quantity: params[:cart_item][:quantity])
    redirect_to request.referrer
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="row">
  <div class="col">
    <% unless cart.cart_items.empty? %>
      <p>
        <table align="center">
          <tr>
            <th>Cart Items</th>
            <th>Item Price</th>
            <th>Item Quantity</th>
          </tr>
          <% cart.cart_items.each do |item| %>
            <tr>
              <td>
                <%= item.food.food_name %>
              </td>
              <td align="center">
                <%= item.food.price %>
              </td>
              <td align="center">
                <%= form_for(item, url: cart_update_carts_path) do |f| %>
                  <%= f.hidden_field :food_id, value: item.food.id %>
                  <%= f.number_field :quantity, in: 1..10,
                  onchange: 'this.form.submit();'%>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
        <hr />
        <%= button_to "Order Food", create_order_orders_path,
        params:{restaurant: @outlet}, class: "btn btn-primary" %>
      </p>
    <% else %>
      <h2>Your Cart is empty!</h2>
    <% end %>
  </div>
</div>