config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  resources :users, only: %i[index show edit update destroy] do
    get '/profile', to: 'users#profile'
  end

  resources :restaurants do
    resources :reviews, only: %i[create destroy]
    # resources :categories, only: %i[new create destroy]
    get '/order', to: 'restaurants#order'
  end

  resources :carts, only: [] do
    collection do
      post 'add_to_cart'
      patch 'cart_update'
      delete 'remove_from_cart'
    end
  end

  resources :orders, only: %i[index show] do
    collection do
      post 'create_order'
      patch 'order_status'
    end
  end

  resources :categories, only: %i[show new create edit update destroy] do
    resources :foods, only: %i[new create]
  end

  resources :foods, only: [:show]

  root 'home_pages#home'

  get '/all_orders', to: 'orders#all_orders'
  get '/help', to: 'home_pages#help'
  get '/about', to: 'home_pages#about'
  get '/contact', to: 'home_pages#contact'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  paginates_per 4

  has_many :reviews, dependent: :destroy
  has_many :restaurant_categories, dependent: :destroy
  has_many :categories, through: :restaurant_categories
  has_many :restaurant_foods, dependent: :destroy
  has_many :foods, through: :restaurant_foods
  has_many :orders, dependent: :destroy

  has_one_attached :restaurant_image

  accepts_nested_attributes_for :restaurant_categories, allow_destroy: true
  accepts_nested_attributes_for :restaurant_foods, allow_destroy: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :restaurant_name, presence: true
  validates :restaurant_address, presence: true
  validates :restaurant_contact, presence: true,
                                 length: { maximum: 10, minimum: 10 }
  validates :restaurant_email, presence: true,
                               format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id restaurant_address restaurant_contact restaurant_details restaurant_email restaurant_image
       restaurant_name status updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[categories foods orders restaurant_categories restaurant_foods restaurant_image_attachment restaurant_image_blob
       reviews]
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @outlets = Restaurant.all.page params[:page]
    authorize @outlets
  end

  def order
    @outlet = Restaurant.find(params[:restaurant_id])
    authorize @outlet
    food_by_category
  end

  def show
    food_by_category
  end

  def new
    authorize @outlet = Restaurant.new
  end

  def create
    authorize @outlet = Restaurant.new(restaurant_params)

    if @outlet.save
      flash[:success] = 'New Restaurant Added'
      redirect_to restaurants_path
    else
      render 'new', status: :see_other
    end
  end

  def edit;  end

  def update
    if @outlet.update(restaurant_params)
      flash[:success] = 'Restaurant details updated'
      redirect_to @outlet
    else
      render 'edit', status: :see_other
    end
  end

  def destroy
    @outlet.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:restaurant_name, :restaurant_email, :restaurant_details, :restaurant_address,
                                       :restaurant_contact, :restaurant_image, :status, category_ids: [], food_ids: [])
  end

  def set_restaurant
    @outlet = Restaurant.find(params[:id])
    authorize @outlet
  end

  def food_by_category
    @food_by_category = @outlet.foods.includes(:category)
                               .group_by { |food| food.category }
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= link_to "Back", :back, class: "btn btn-outline-dark"%>
<div class="row">
  <div class="col-md-4 mx-auto">
    <%= form_with model: outlet do |f|%>
      <%= render"shared/error_messages", object: outlet %>

      <div>
        <%= f.label :restaurant_name %><br>
        <%= f.text_field :restaurant_name, class: "form-control mb-3" %>
      </div>
      
      <div>
        <%= f.label :restaurant_email %><br>
        <%= f.email_field :restaurant_email, class: "form-control mb-3" %>
      </div>
      
      <div>
        <%= f.label :restaurant_contact %><br>
        <%= f.telephone_field :restaurant_contact, class: "form-control mb-3" %>
      </div>
      
      <div>
        <%= f.label :restaurant_details %><br>
        <%= f.text_area :restaurant_details, class: "form-control mb-3" %>
      </div>
      
      <div>
        <%= f.label :restaurant_address %><br>
        <%= f.text_area :restaurant_address, class: "form-control mb-3 " %>
      </div>

      <div>
        <%= f.label :restaurant_image %><br>
        <%= f.file_field :restaurant_image, class: "form-control mb-3 " %>
      </div>

      <div>
        <%= f.label :status, class: "mb-3" %><br>
        <%= f.select :status, ['Open', 'Closed'], selected: 'Open' %>
      </div>

      <div class="col-md-3">
        <%= f.label :category_ids, 'Categories', class:"my-3" %><br>
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :category_name)%>
      </div>

        <%= f.label :food_ids, 'Foods', class: 'my-3'%><br>
      <div class="row">
          <%= f.collection_check_boxes(:food_ids, Food.all, :id, :food_name) do |cb| %>
            <%= cb.label(class:"check_box") do %>
              <%= cb.check_box(class:"check_box")%>
              <%= cb.object.food_name%><br />
            <% end %>
          <% end %>
      </div>

      <%= f.submit "save", class: "btn btn-primary mt-3" %>
    <% end %>
  </div>
</div>

app/views/restaurants/_menu.html.erb
<div class="row">
  <div class="col-md-6 mx-auto">
    <% menu.each do |category, foods|%>
      <div class="accordion">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              <h3> <%= category.category_name%> </h3>
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <p>
                <% foods.each do |food| %>
                  <li style="padding-left:20px; list-style-type: none">
                    <%= food.food_name %> | <%= food.price %> <br />
                    <hr />
                  </li>
                <% end %>
              </p>  
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render 'form', outlet: @outlet%>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>
<%= button_to "Add New Restaurant", new_restaurant_path, 
class: "btn btn-primary", style: "float:right", method: :get if admin? %>
<div class="row">
  <% @outlets.each do |outlet| %>
    <div class="col-md-3">
      <div class="card-group">
        <div class="card mb-3">
          <div class="card-header">
            <%= outlet.restaurant_name %>
          </div>
          <a href=<%= restaurant_path(outlet)%> class="card-body">
            <%= image_tag outlet.restaurant_image, size: "225x200"%>
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>
<nav class="pagination justify-content-center">
  <%= paginate @outlets %>
</nav>

app/views/restaurants/new.html.erb
<h1>Add Restaurant</h1>
<%= render 'form', outlet: @outlet %>

app/views/restaurants/order.html.erb
<h1>Order Food</h1>
<%= link_to "Back", restaurant_path(params[:restaurant_id]), class: "btn btn-outline-dark"%>
<div class="row">
  <div class="col-md-4 order-food">
    <h2>Categories</h2>
    <% @food_by_category.each do |category, foods| %>
      <div class="accordion">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              <h3> <%= category.category_name%> </h3>
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <p>
                <% foods.each do |food| %>
                  <li style="padding-left:20px; list-style-type: none">
                    <%= food.food_name %> | <%= food.price %> <br />
                    <% if cart_item_exist?(food) %>
                      <%= button_to "Remove From Cart",  remove_from_cart_carts_path,  params: {food_id: food},
                      class: "btn btn-danger", method: :delete %>
                    <% else %>
                      <%= button_to "Add To Cart", add_to_cart_carts_path, params: {food_id: food}, class: "btn btn-primary" %>
                    <% end %>
                    <hr />
                  </li>
                <% end %>
              </p>  
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-4 order-food">
    <h2> Cart </h2>
    <%= render current_user.cart %>
  </div>
  <div class="col">
    <h2> Order </h2>
    <%= render current_user.orders %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="row">
  <h1><%= @outlet.restaurant_name %></h1>
  <div class="col">
    <p>
    <%= @outlet.restaurant_details %><br />
    <%= @outlet.restaurant_address %><br />
    <%= @outlet.status %><br />
    </p>
    <hr />
    <ul class="nav">
      <li class="nav-item me-3">
        <%= link_to "Order Food", restaurant_order_path(@outlet), class: "btn btn-primary mb-3"%>
      </li>
      <% if admin? %>
        <li class="nav-item me-3">
          <%= link_to "Edit Details", edit_restaurant_path, class:"btn btn-primary mb-3"%>
        </li>
        <li class="nav-item me-3">
          <%= button_to "Delete Restaurant", restaurant_path(@outlet), 
          class:"btn btn-primary mb-3", data: {turbo_method: :delete, 
                                        turbo_confirm: "are you sure?"} %>
        </li>
      <% end %>
    </ul>
    <hr />
  </div>
</div>
<div class="row">
  <div class="col-md-6 order-food">
    <h2>Reviews</h2>
    <%= render @outlet.reviews %>
    <%= render 'reviews/review_form' %>
  </div>
  <div class="col-md-6">
    <h2>Menu</h2>
    <%= render 'menu', menu: @food_by_category %>
  </div>
</div>