config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  resources :users, only: %i[index show edit update destroy] do
    get '/profile', to: 'users#profile'
  end

  resources :restaurants do
    resources :reviews, only: %i[create destroy]
    # resources :categories, only: %i[new create destroy]
    get '/order', to: 'restaurants#order'
  end

  resources :carts, only: [] do
    collection do
      post 'add_to_cart'
      patch 'cart_update'
      delete 'remove_from_cart'
    end
  end

  resources :orders, only: %i[index show] do
    collection do
      post 'create_order'
      patch 'order_status'
    end
  end

  resources :categories, only: %i[show new create edit update destroy] do
    resources :foods, only: %i[new create]
  end

  resources :foods, only: [:show]

  root 'home_pages#home'

  get '/all_orders', to: 'orders#all_orders'
  get '/help', to: 'home_pages#help'
  get '/about', to: 'home_pages#about'
  get '/contact', to: 'home_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :cart_items
  has_many :foods, through: :cart_items

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id restaurant_id updated_at user_id]
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :food

  # validates :quantity, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :restaurant_categories, dependent: :destroy
  has_many :restaurants, through: :restaurant_categories
  has_many :foods, dependent: :destroy

  has_one_attached :category_image

  validates :category_name, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[category_image category_name created_at id updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[category_image_attachment category_image_blob foods restaurant_categories restaurants]
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
  has_many :restaurant_foods, dependent: :destroy
  has_many :restaurants, through: :restaurant_foods

  validates :food_name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }

  def self.ransackable_attributes(_auth_object = nil)
    %w[category_id created_at food_name id price updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[category restaurant_foods restaurants]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  paginates_per 5

  belongs_to :user
  belongs_to :restaurant
  has_many :order_items
  has_many :foods, through: :order_items

  enum :order_status, %i[pending accepted rejected], default: :pending

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id order_status restaurant_id total_amount updated_at user_id]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[foods order_items restaurant user]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :food

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at food_id id order_id quantity updated_at]
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  paginates_per 4

  has_many :reviews, dependent: :destroy
  has_many :restaurant_categories, dependent: :destroy
  has_many :categories, through: :restaurant_categories
  has_many :restaurant_foods, dependent: :destroy
  has_many :foods, through: :restaurant_foods
  has_many :orders, dependent: :destroy

  has_one_attached :restaurant_image

  accepts_nested_attributes_for :restaurant_categories, allow_destroy: true
  accepts_nested_attributes_for :restaurant_foods, allow_destroy: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :restaurant_name, presence: true
  validates :restaurant_address, presence: true
  validates :restaurant_contact, presence: true,
                                 length: { maximum: 10, minimum: 10 }
  validates :restaurant_email, presence: true,
                               format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id restaurant_address restaurant_contact restaurant_details restaurant_email restaurant_image
       restaurant_name status updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[categories foods orders restaurant_categories restaurant_foods restaurant_image_attachment restaurant_image_blob
       reviews]
  end
end

app/models/restaurant_food.rb
class RestaurantFood < ApplicationRecord
  belongs_to :restaurant
  belongs_to :food

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at food_id id price restaurant_id updated_at]
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  def self.ransackable_attributes(_auth_object = nil)
    %w[content created_at id restaurant_id updated_at user_id]
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true


  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify

  def self.ransackable_associations(_auth_object = nil)
    %w[resource users]
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id name resource_id resource_type updated_at]
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  paginates_per 5

  after_create :assign_default_role

  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :reviews
  has_one :cart
  has_many :orders

  validates :username, presence: true, length: { maximum: 15 }
  validates :email, length: { maximum: 255 }, format: { with: email_regexp }
  validates :address, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[address confirmation_sent_at confirmation_token confirmed_at created_at email encrypted_password id
       remember_created_at reset_password_sent_at reset_password_token unconfirmed_email updated_at username]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[cart orders reviews roles]
  end

  private

  def assign_default_role
    add_role(:member) if roles.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Food Vault'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end

  def admin?
    current_user.has_role? :admin
  end

  def set_cart
    if current_user.cart.present?
      current_user.cart
    else
      Cart.create(restaurant_id: params[:restaurant_id], user: current_user)
    end
  end

  def cart_item_exist?(food)
    cart_item = set_cart.cart_items.find_by(food:)
    cart_item.present?
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, option = { size: 80 })
    size = option[:size]
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://github.com/chiragtiwari2001/Food_Circle_Application">Food Circle</a>
    by <a href="https://github.com/chiragtiwari2001">Chirag Tiwari</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar fixed-top navbar-expand-lg bg-warning navbar-llight">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to "FOOD-CIRCLE", root_path, id: "logo" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %> 
          <li>
            <%= link_to "All Outlets", restaurants_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Home", root_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "My orders", orders_path, class: "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle dropdown-left" href="#" role="button" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu dropdown-menu-lg-end dropdown-menu-dark">
              <li>
                <%= link_to "Profile", user_profile_path(current_user), class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <% if admin? %>
                <li>
                  <%= link_to "All Orders", all_orders_path, 
                  class: "dropdown-item"%>
                </li>
                <li>
                  <%= link_to "Admin Panel", admin_root_path, class:"dropdown-item"%>
                </li>
              <% end %>
              <li>
                <%= button_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <%= button_to "Sign in", new_user_session_path, class:"btn btn-primary" %> 
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= render 'layouts/header' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <nav class="mt-auto">
        <%= render 'layouts/footer'%>
      </nav>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>